---
before:
  hooks:
    - ./bld/completions.sh
builds:
  - id: tptctl
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    main: ./
    binary: tptctl
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - completions/*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-snapshot-{{.ShortCommit}}"
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs(\(.*\))?:'
      - '^test(\(.*\))?:'
      - '^ci(\(.*\))?:'
      - '^chore(\(.*\))?:'
      - '^build(\(.*\))?:'
brews:
  - name: tptctl
    tap:
      owner: threeport
      name: homebrew-tap
      token: "{{ .Env.GH_ACCESS_TOKEN }}"

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: goreleaserbot
      email: goreleaser@threeport.io

    # Folder inside the repository to put the formula.
    # Default is the root folder.
    folder: Formula

    # Your app's homepage.
    # Default is empty.
    homepage: "https://github.com/threeport/{{ .ProjectName }}"

    # Template of your app's description.
    # Default is empty.
    description: "A CLI for managing workloads on Threeport."

    # SPDX identifier of your app's license.
    # Default is empty.
    license: "MIT"

    # Setting this will prevent goreleaser to actually try to commit the updated
    # formula - instead, the formula file will be stored on the dist folder only,
    # leaving the responsibility of publishing it to the user.
    # If set to auto, the release will not be uploaded to the homebrew tap
    # in case there is an indicator for prerelease in the tag e.g. v1.0.0-rc1
    # Default is false.
    skip_upload: auto

    # Packages your package depends on.
    dependencies:
      - name: docker
      - name: kubectl
      - name: kind
      - name: wget
      - name: jq

    install: |-
      bin.install "{{ .ProjectName }}"
      bash_completion.install "completions/{{ .ProjectName }}.bash" => "{{ .ProjectName }}"
      zsh_completion.install "completions/{{ .ProjectName }}.zsh" => "_{{ .ProjectName }}"
      fish_completion.install "completions/{{ .ProjectName }}.fish"

    # So you can `brew test` your formula.
    # Default is empty.
    test: |
      system "#{bin}/{{ .ProjectName }} version"

nfpms:
  - file_name_template: 'tptctl_v{{ .Version }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage: https://github.com/threeport/{{ .ProjectName }}
    description: "A CLI for managing workloads on Threeport."
    maintainer: Andriy Kalashnykov <AndriyKalashnykov@gmail.com>
    license: MIT
    vendor: threeport
    contents:
      - src: ./completions/{{ .ProjectName }}.bash
        dst: /etc/bash_completion.d/{{ .ProjectName }}
      - src: ./completions/{{ .ProjectName }}.fish
        dst: /usr/share/fish/completions/{{ .ProjectName }}.fish
      - src: ./completions/{{ .ProjectName }}.zsh
        dst: /usr/local/share/zsh/site-functions/_{{ .ProjectName }}
    formats:
      - apk
      - deb
      - rpm
    recommends:
      - docker
      - kubectl
      - kind
      - wget
      - jq
